dist: xenial
language: php

script:
  # Run a syntax validation check on all PHP files
  -  find . -path  -prune -o -iname '*.php' |xargs -n1 php -l
  
before_deploy:
  - zip -r@ "htmlparse-php.zip"  
  
deploy:
  provider: releases
  # Otherwise, we lose the vendor/ directory
  skip_cleanup: true
  api_key: 121773b50e7b26d623ede05e3fd0fc31ff08315b
  # travis doesn't support multi file deployes yet, not that we need them
  file: htmlparse-php.zip
  on:
    # Only do the release for one build every tag
    php: 5.6
    # GitHub refuses to accept releases that are not tagged
    tags: true
    # Allow builds for non-master branches as well
    all_branches: true
    # Only do the releases if the repo is not a fork
    repo: ramth05/htmlparserphp
