dist: precise
language: php


deploy:
  provider: releases
  # Otherwise, we lose the vendor/ directory
  skip_cleanup: true

  # travis doesn't support multi file deployes yet, not that we need them
  file: htmlparse-php.zip
  on:
    # Only do the release for one build every tag
    php: 5.6
    # GitHub refuses to accept releases that are not tagged
    tags: true
    # Allow builds for non-master branches as well
    all_branches: true
    # Only do the releases if the repo is not a fork
    repo: ramth05/htmlparserphp
